import type { GLTF } from './types';

import { useGLTF } from '@react-three/drei';
import { Box3, Vector3 } from 'three';
import { useEffect, useState } from 'react';

import { animated, useSpring } from '@react-spring/three';

import { getIssScaledLength } from './helpers';
import useWhereIsISS from './useWhereIsISS';

const path = '/models/iss.glb';

export default function Model() {
	const model = useGLTF(path);
	const { nodes, materials } = model as GLTF;

	const [scale, setScale] = useState(0);

	useEffect(() => {
		const bb = new Box3();
		bb.setFromObject(model.scene);

		const length = bb.max.y - bb.min.y;
		const scaledLength = getIssScaledLength(length);

		setScale(scaledLength * 5000);
	}, [model]);

	const coords = useWhereIsISS();

	const { position } = useSpring({
		position: coords,
		config: { duration: 2000 },
	});

	return (
		<animated.group
			dispose={null}
			position={position as unknown as Vector3}
			scale={scale}
		>
			<mesh
				geometry={nodes.Cylinder022.geometry}
				material={nodes.Cylinder022.material}
			/>
			<mesh
				geometry={nodes.Cylinder022_1.geometry}
				material={nodes.Cylinder022_1.material}
			/>
			<mesh
				geometry={nodes.Cylinder022_2.geometry}
				material={nodes.Cylinder022_2.material}
			/>
			<mesh
				geometry={nodes.Cylinder022_3.geometry}
				material={nodes.Cylinder022_3.material}
			/>
			<group position={[0, 0, -3.38]}>
				<mesh
					geometry={nodes.Cylinder001.geometry}
					material={nodes.Cylinder001.material}
				/>
				<mesh
					geometry={nodes.Cylinder001_1.geometry}
					material={nodes.Cylinder001_1.material}
				/>
				<mesh
					geometry={nodes.Cylinder001_2.geometry}
					material={nodes.Cylinder001_2.material}
				/>
				<group position={[0, 0.73, -2.46]}>
					<mesh
						geometry={nodes.Sphere002.geometry}
						material={nodes.Sphere002.material}
					/>
					<mesh
						geometry={nodes.Sphere002_1.geometry}
						material={nodes.Sphere002_1.material}
					/>
					<mesh
						geometry={nodes.Sphere002_2.geometry}
						material={nodes.Sphere002_2.material}
					/>
					<mesh
						geometry={nodes.Sphere002_3.geometry}
						material={nodes.Sphere002_3.material}
					/>
					<group position={[0, 0, -12.96]}>
						<mesh
							geometry={nodes.sm_ext_sm000.geometry}
							material={nodes.sm_ext_sm000.material}
						/>
						<mesh
							geometry={nodes.sm_ext_sm000_1.geometry}
							material={nodes.sm_ext_sm000_1.material}
						/>
						<mesh
							geometry={nodes.sm_ext_sm000_2.geometry}
							material={nodes.sm_ext_sm000_2.material}
						/>
						<mesh
							geometry={nodes.sm_ext_sm000_3.geometry}
							material={nodes.sm_ext_sm000_3.material}
						/>
						<mesh
							geometry={nodes.sm_ext_sm000_4.geometry}
							material={nodes.sm_ext_sm000_4.material}
						/>
						<group position={[0, -1.16, -1.16]}>
							<mesh
								geometry={nodes.Sphere001.geometry}
								material={nodes.Sphere001.material}
							/>
							<mesh
								geometry={nodes.Sphere001_1.geometry}
								material={nodes.Sphere001_1.material}
							/>
							<mesh
								geometry={nodes.Sphere001_2.geometry}
								material={nodes.Sphere001_2.material}
							/>
							<mesh
								geometry={nodes.Sphere001_3.geometry}
								material={nodes.Sphere001_3.material}
							/>
						</group>
						<group position={[0, 1.16, -1.16]}>
							<mesh
								geometry={nodes.Sphere003.geometry}
								material={nodes.Sphere003.material}
							/>
							<mesh
								geometry={nodes.Sphere003_1.geometry}
								material={nodes.Sphere003_1.material}
							/>
							<mesh
								geometry={nodes.Sphere003_2.geometry}
								material={nodes.Sphere003_2.material}
							/>
							<mesh
								geometry={nodes.Sphere003_3.geometry}
								material={nodes.Sphere003_3.material}
							/>
						</group>
						<group position={[2.23, -0.03, -5.26]}>
							<mesh
								geometry={nodes.sm_ext_sm001.geometry}
								material={nodes.sm_ext_sm001.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm001_1.geometry}
								material={nodes.sm_ext_sm001_1.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm001_2.geometry}
								material={nodes.sm_ext_sm001_2.material}
							/>
						</group>
						<group position={[-2.23, -0.03, -5.26]}>
							<mesh
								geometry={nodes.sm_ext_sm002.geometry}
								material={nodes.sm_ext_sm002.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm002_1.geometry}
								material={nodes.sm_ext_sm002_1.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm002_2.geometry}
								material={nodes.sm_ext_sm002_2.material}
							/>
						</group>
						<group position={[3.51, -0.03, -5.26]}>
							<mesh
								geometry={nodes.sm_ext_sm003.geometry}
								material={nodes.sm_ext_sm003.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm003_1.geometry}
								material={nodes.sm_ext_sm003_1.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm003_2.geometry}
								material={nodes.sm_ext_sm003_2.material}
							/>
						</group>
						<group position={[-3.51, -0.03, -5.26]}>
							<mesh
								geometry={nodes.sm_ext_sm004.geometry}
								material={nodes.sm_ext_sm004.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm004_1.geometry}
								material={nodes.sm_ext_sm004_1.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm004_2.geometry}
								material={nodes.sm_ext_sm004_2.material}
							/>
						</group>
						<group position={[5.03, -0.03, -5.26]}>
							<mesh
								geometry={nodes.sm_ext_sm005.geometry}
								material={nodes.sm_ext_sm005.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm005_1.geometry}
								material={nodes.sm_ext_sm005_1.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm005_2.geometry}
								material={nodes.sm_ext_sm005_2.material}
							/>
						</group>
						<group position={[-5.03, -0.03, -5.26]}>
							<mesh
								geometry={nodes.sm_ext_sm006.geometry}
								material={nodes.sm_ext_sm006.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm006_1.geometry}
								material={nodes.sm_ext_sm006_1.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm006_2.geometry}
								material={nodes.sm_ext_sm006_2.material}
							/>
						</group>
						<group position={[6.56, -0.03, -5.26]}>
							<mesh
								geometry={nodes.sm_ext_sm007.geometry}
								material={nodes.sm_ext_sm007.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm007_1.geometry}
								material={nodes.sm_ext_sm007_1.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm007_2.geometry}
								material={nodes.sm_ext_sm007_2.material}
							/>
						</group>
						<group position={[-6.56, -0.03, -5.26]}>
							<mesh
								geometry={nodes.sm_ext_sm008.geometry}
								material={nodes.sm_ext_sm008.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm008_1.geometry}
								material={nodes.sm_ext_sm008_1.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm008_2.geometry}
								material={nodes.sm_ext_sm008_2.material}
							/>
						</group>
						<group position={[8.07, -0.03, -5.26]}>
							<mesh
								geometry={nodes.sm_ext_sm009.geometry}
								material={nodes.sm_ext_sm009.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm009_1.geometry}
								material={nodes.sm_ext_sm009_1.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm009_2.geometry}
								material={nodes.sm_ext_sm009_2.material}
							/>
						</group>
						<group position={[-8.07, -0.03, -5.26]}>
							<mesh
								geometry={nodes.sm_ext_sm010.geometry}
								material={nodes.sm_ext_sm010.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm010_1.geometry}
								material={nodes.sm_ext_sm010_1.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm010_2.geometry}
								material={nodes.sm_ext_sm010_2.material}
							/>
						</group>
						<group position={[9.58, -0.03, -5.26]}>
							<mesh
								geometry={nodes.sm_ext_sm011.geometry}
								material={nodes.sm_ext_sm011.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm011_1.geometry}
								material={nodes.sm_ext_sm011_1.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm011_2.geometry}
								material={nodes.sm_ext_sm011_2.material}
							/>
						</group>
						<group position={[-9.58, -0.03, -5.26]}>
							<mesh
								geometry={nodes.sm_ext_sm012.geometry}
								material={nodes.sm_ext_sm012.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm012_1.geometry}
								material={nodes.sm_ext_sm012_1.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm012_2.geometry}
								material={nodes.sm_ext_sm012_2.material}
							/>
						</group>
						<group position={[11.16, -0.03, -5.26]}>
							<mesh
								geometry={nodes.sm_ext_sm013.geometry}
								material={nodes.sm_ext_sm013.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm013_1.geometry}
								material={nodes.sm_ext_sm013_1.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm013_2.geometry}
								material={nodes.sm_ext_sm013_2.material}
							/>
						</group>
						<group position={[-11.16, -0.03, -5.26]}>
							<mesh
								geometry={nodes.sm_ext_sm014.geometry}
								material={nodes.sm_ext_sm014.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm014_1.geometry}
								material={nodes.sm_ext_sm014_1.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm014_2.geometry}
								material={nodes.sm_ext_sm014_2.material}
							/>
						</group>
						<group position={[12.74, -0.03, -5.26]}>
							<mesh
								geometry={nodes.sm_ext_sm015.geometry}
								material={nodes.sm_ext_sm015.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm015_1.geometry}
								material={nodes.sm_ext_sm015_1.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm015_2.geometry}
								material={nodes.sm_ext_sm015_2.material}
							/>
						</group>
						<group position={[-12.74, -0.03, -5.26]}>
							<mesh
								geometry={nodes.sm_ext_sm016.geometry}
								material={nodes.sm_ext_sm016.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm016_1.geometry}
								material={nodes.sm_ext_sm016_1.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm016_2.geometry}
								material={nodes.sm_ext_sm016_2.material}
							/>
						</group>
						<group position={[14.33, -0.03, -5.26]}>
							<mesh
								geometry={nodes.sm_ext_sm017.geometry}
								material={nodes.sm_ext_sm017.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm017_1.geometry}
								material={nodes.sm_ext_sm017_1.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm017_2.geometry}
								material={nodes.sm_ext_sm017_2.material}
							/>
						</group>
						<group position={[-14.33, -0.03, -5.26]}>
							<mesh
								geometry={nodes.sm_ext_sm018.geometry}
								material={nodes.sm_ext_sm018.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm018_1.geometry}
								material={nodes.sm_ext_sm018_1.material}
							/>
							<mesh
								geometry={nodes.sm_ext_sm018_2.geometry}
								material={nodes.sm_ext_sm018_2.material}
							/>
						</group>
						<mesh
							geometry={nodes.panel_bracket_p.geometry}
							material={nodes.panel_bracket_p.material}
							position={[1.9, -0.03, -5.26]}
						/>
						<mesh
							geometry={nodes.panel_bracket_s.geometry}
							material={nodes.panel_bracket_s.material}
							position={[-1.9, -0.03, -5.26]}
						/>
					</group>
					<group position={[0, -4.59, -1.15]}>
						<mesh
							geometry={nodes.Sphere004.geometry}
							material={nodes.Sphere004.material}
						/>
						<mesh
							geometry={nodes.Sphere004_1.geometry}
							material={nodes.Sphere004_1.material}
						/>
						<mesh
							geometry={nodes.Sphere004_2.geometry}
							material={nodes.Sphere004_2.material}
						/>
						<mesh
							geometry={nodes.Sphere004_3.geometry}
							material={nodes.Sphere004_3.material}
						/>
					</group>
				</group>
			</group>
			<group position={[0, 1.76, 0]}>
				<mesh
					geometry={nodes.z1_ext_01001.geometry}
					material={nodes.z1_ext_01001.material}
				/>
				<mesh
					geometry={nodes.z1_ext_01001_1.geometry}
					material={nodes.z1_ext_01001_1.material}
				/>
				<mesh
					geometry={nodes.z1_ext_01001_2.geometry}
					material={nodes.z1_ext_01001_2.material}
				/>
				<mesh
					geometry={nodes.z1_ext_01001_3.geometry}
					material={materials['ISS_01_dark *']}
				/>
				<mesh
					geometry={nodes.z1_ext_01001_4.geometry}
					material={nodes.z1_ext_01001_4.material}
				/>
			</group>
			<group position={[0, 0, 2.22]}>
				<mesh
					geometry={nodes.Cylinder002.geometry}
					material={nodes.Cylinder002.material}
				/>
				<mesh
					geometry={nodes.Cylinder002_1.geometry}
					material={nodes.Cylinder002_1.material}
				/>
				<mesh
					geometry={nodes.Cylinder002_2.geometry}
					material={nodes.Cylinder002_2.material}
				/>
				<mesh
					geometry={nodes.Cylinder002_3.geometry}
					material={nodes.Cylinder002_3.material}
				/>
				<mesh
					geometry={nodes.Cylinder002_4.geometry}
					material={nodes.Cylinder002_4.material}
				/>
				<mesh
					geometry={nodes.Cylinder002_5.geometry}
					material={nodes.Cylinder002_5.material}
				/>
				<group position={[2.73, -0.48, 2.01]}>
					<mesh
						geometry={nodes.z1_ext_01002.geometry}
						material={nodes.z1_ext_01002.material}
					/>
					<mesh
						geometry={nodes.z1_ext_01002_1.geometry}
						material={nodes.z1_ext_01002_1.material}
					/>
				</group>
				<group position={[0, 5.01, 0.97]}>
					<mesh
						geometry={nodes.s0_ani000.geometry}
						material={nodes.s0_ani000.material}
					/>
					<mesh
						geometry={nodes.s0_ani000_1.geometry}
						material={nodes.s0_ani000_1.material}
					/>
					<mesh
						geometry={nodes.s0_ani000_2.geometry}
						material={nodes.s0_ani000_2.material}
					/>
					<mesh
						geometry={nodes.s0_ani000_3.geometry}
						material={nodes.s0_ani000_3.material}
					/>
					<mesh
						geometry={nodes.s0_ani000_4.geometry}
						material={nodes.s0_ani000_4.material}
					/>
					<group position={[-2.87, -0.6, 5.17]}>
						<mesh
							geometry={nodes.mss_mbs001.geometry}
							material={nodes.mss_mbs001.material}
						/>
						<mesh
							geometry={nodes.mss_mbs001_1.geometry}
							material={nodes.mss_mbs001_1.material}
						/>
						<mesh
							geometry={nodes.mss_mbs001_2.geometry}
							material={nodes.mss_mbs001_2.material}
						/>
						<mesh
							geometry={nodes.mss_mbs001_3.geometry}
							material={nodes.mss_mbs001_3.material}
						/>
						<mesh
							geometry={nodes['11_Canadarm2'].geometry}
							material={nodes['11_Canadarm2'].material}
							position={[-1.43, 1.59, 0.2]}
						>
							<mesh
								geometry={nodes['11_Canadarm2_02'].geometry}
								material={nodes['11_Canadarm2_02'].material}
								position={[-0.67, 0.36, 0.98]}
							>
								<mesh
									geometry={nodes['11_Canadarm2_03'].geometry}
									material={nodes['11_Canadarm2_03'].material}
									position={[-0.01, 0.36, 0.23]}
								>
									<mesh
										geometry={
											nodes['11_Canadarm2_04'].geometry
										}
										material={
											nodes['11_Canadarm2_04'].material
										}
										position={[0.13, 0.25, 0.31]}
									>
										<mesh
											geometry={
												nodes['11_Canadarm2_05']
													.geometry
											}
											material={
												nodes['11_Canadarm2_05']
													.material
											}
											position={[-7.34, 0, 0.58]}
										>
											<mesh
												geometry={
													nodes['11_Canadarm2_06']
														.geometry
												}
												material={
													nodes['11_Canadarm2_06']
														.material
												}
												position={[0, 7.34, 0.58]}
											>
												<mesh
													geometry={
														nodes['11_Canadarm2_07']
															.geometry
													}
													material={
														nodes['11_Canadarm2_07']
															.material
													}
													position={[-0.29, 0, 0.31]}
												>
													<mesh
														geometry={
															nodes[
																'11_Canadarm2_08'
															].geometry
														}
														material={
															nodes[
																'11_Canadarm2_08'
															].material
														}
														position={[
															-0.31, 0.29, 0,
														]}
													>
														<group
															position={[
																0, 1.2, 0,
															]}
														>
															<mesh
																geometry={
																	nodes
																		.Cylinder009
																		.geometry
																}
																material={
																	nodes
																		.Cylinder009
																		.material
																}
															/>
															<mesh
																geometry={
																	nodes
																		.Cylinder009_1
																		.geometry
																}
																material={
																	nodes
																		.Cylinder009_1
																		.material
																}
															/>
															<mesh
																geometry={
																	nodes[
																		'29_DEXTRE001'
																	].geometry
																}
																material={
																	nodes[
																		'29_DEXTRE001'
																	].material
																}
																position={[
																	0, 0.22, 0,
																]}
															>
																<mesh
																	geometry={
																		nodes[
																			'29_DEXTRE002'
																		]
																			.geometry
																	}
																	material={
																		nodes[
																			'29_DEXTRE002'
																		]
																			.material
																	}
																	position={[
																		0, 1.96,
																		0.01,
																	]}
																>
																	<mesh
																		geometry={
																			nodes[
																				'29_DEXTRE003'
																			]
																				.geometry
																		}
																		material={
																			nodes[
																				'29_DEXTRE003'
																			]
																				.material
																		}
																		position={[
																			0,
																			0.96,
																			0,
																		]}
																	/>
																</mesh>
																<mesh
																	geometry={
																		nodes[
																			'29_DEXTRE004'
																		]
																			.geometry
																	}
																	material={
																		nodes[
																			'29_DEXTRE004'
																		]
																			.material
																	}
																	position={[
																		1.38,
																		1.43, 0,
																	]}
																>
																	<mesh
																		geometry={
																			nodes[
																				'29_DEXTRE005'
																			]
																				.geometry
																		}
																		material={
																			nodes[
																				'29_DEXTRE005'
																			]
																				.material
																		}
																		position={[
																			0.37,
																			-0.1,
																			0.27,
																		]}
																	>
																		<mesh
																			geometry={
																				nodes[
																					'29_DEXTRE006'
																				]
																					.geometry
																			}
																			material={
																				nodes[
																					'29_DEXTRE006'
																				]
																					.material
																			}
																			position={[
																				0.3,
																				-0.11,
																				0.14,
																			]}
																		>
																			<mesh
																				geometry={
																					nodes[
																						'29_DEXTRE007'
																					]
																						.geometry
																				}
																				material={
																					nodes[
																						'29_DEXTRE007'
																					]
																						.material
																				}
																				position={[
																					1.09,
																					0.01,
																					0.06,
																				]}
																			>
																				<mesh
																					geometry={
																						nodes[
																							'29_DEXTRE008'
																						]
																							.geometry
																					}
																					material={
																						nodes[
																							'29_DEXTRE008'
																						]
																							.material
																					}
																					position={[
																						1.09,
																						-0.01,
																						-0.33,
																					]}
																				>
																					<mesh
																						geometry={
																							nodes[
																								'29_DEXTRE009'
																							]
																								.geometry
																						}
																						material={
																							nodes[
																								'29_DEXTRE009'
																							]
																								.material
																						}
																						position={[
																							0.28,
																							-0.12,
																							-0.11,
																						]}
																					/>
																				</mesh>
																			</mesh>
																		</mesh>
																	</mesh>
																</mesh>
																<mesh
																	geometry={
																		nodes[
																			'29_DEXTRE010'
																		]
																			.geometry
																	}
																	material={
																		nodes[
																			'29_DEXTRE010'
																		]
																			.material
																	}
																	position={[
																		-1.38,
																		1.43, 0,
																	]}
																>
																	<mesh
																		geometry={
																			nodes[
																				'29_DEXTRE011'
																			]
																				.geometry
																		}
																		material={
																			nodes[
																				'29_DEXTRE011'
																			]
																				.material
																		}
																		position={[
																			-0.37,
																			-0.1,
																			0.27,
																		]}
																	>
																		<mesh
																			geometry={
																				nodes[
																					'29_DEXTRE012'
																				]
																					.geometry
																			}
																			material={
																				nodes[
																					'29_DEXTRE012'
																				]
																					.material
																			}
																			position={[
																				-0.3,
																				-0.11,
																				0.14,
																			]}
																		>
																			<mesh
																				geometry={
																					nodes[
																						'29_DEXTRE013'
																					]
																						.geometry
																				}
																				material={
																					nodes[
																						'29_DEXTRE013'
																					]
																						.material
																				}
																				position={[
																					-1.09,
																					0.01,
																					0.06,
																				]}
																			>
																				<mesh
																					geometry={
																						nodes[
																							'29_DEXTRE014'
																						]
																							.geometry
																					}
																					material={
																						nodes[
																							'29_DEXTRE014'
																						]
																							.material
																					}
																					position={[
																						-1.09,
																						-0.01,
																						-0.33,
																					]}
																				>
																					<mesh
																						geometry={
																							nodes[
																								'29_DEXTRE015'
																							]
																								.geometry
																						}
																						material={
																							nodes[
																								'29_DEXTRE015'
																							]
																								.material
																						}
																						position={[
																							-0.28,
																							-0.12,
																							-0.11,
																						]}
																					/>
																				</mesh>
																			</mesh>
																		</mesh>
																	</mesh>
																</mesh>
															</mesh>
														</group>
													</mesh>
												</mesh>
											</mesh>
										</mesh>
									</mesh>
								</mesh>
							</mesh>
						</mesh>
					</group>
					<group position={[-13.81, 0, 2.44]}>
						<mesh
							geometry={nodes.s0_ani001.geometry}
							material={nodes.s0_ani001.material}
						/>
						<mesh
							geometry={nodes.s0_ani001_1.geometry}
							material={nodes.s0_ani001_1.material}
						/>
						<mesh
							geometry={nodes.s0_ani001_2.geometry}
							material={nodes.s0_ani001_2.material}
						/>
						<mesh
							geometry={nodes.s0_ani001_3.geometry}
							material={nodes.s0_ani001_3.material}
						/>
						<mesh
							geometry={nodes.s0_ani001_4.geometry}
							material={nodes.s0_ani001_4.material}
						/>
						<group position={[-1.44, -0.01, -0.94]}>
							<mesh
								geometry={nodes.s0_ani002.geometry}
								material={nodes.s0_ani002.material}
							/>
							<mesh
								geometry={nodes.s0_ani002_1.geometry}
								material={nodes.s0_ani002_1.material}
							/>
							<mesh
								geometry={nodes.s0_ani002_2.geometry}
								material={nodes.s0_ani002_2.material}
							/>
							<mesh
								geometry={nodes.s0_ani002_3.geometry}
								material={nodes.s0_ani002_3.material}
							/>
						</group>
						<group position={[-10.05, 0.01, -0.82]}>
							<mesh
								geometry={nodes.s0_ani003.geometry}
								material={nodes.s0_ani003.material}
							/>
							<mesh
								geometry={nodes.s0_ani003_1.geometry}
								material={nodes.s0_ani003_1.material}
							/>
							<mesh
								geometry={nodes.s0_ani003_2.geometry}
								material={nodes.s0_ani003_2.material}
							/>
							<group
								position={[-3.02, -0.03, -0.01]}
								rotation={[Math.PI / 3, 0, 0]}
							>
								<mesh
									geometry={nodes.p6_ani000.geometry}
									material={nodes.p6_ani000.material}
								/>
								<mesh
									geometry={nodes.p6_ani000_1.geometry}
									material={nodes.p6_ani000_1.material}
								/>
								<mesh
									geometry={nodes.p6_ani000_2.geometry}
									material={nodes.p6_ani000_2.material}
								/>
								<mesh
									geometry={nodes.p6_ani000_3.geometry}
									material={nodes.p6_ani000_3.material}
								/>
								<mesh
									geometry={nodes.p6_ani000_4.geometry}
									material={nodes.p6_ani000_4.material}
								/>
								<group position={[-8.14, -0.01, 1.23]}>
									<mesh
										geometry={nodes.Cube004.geometry}
										material={nodes.Cube004.material}
									/>
									<mesh
										geometry={nodes.Cube004_1.geometry}
										material={nodes.Cube004_1.material}
									/>
									<mesh
										geometry={nodes.Cube004_2.geometry}
										material={nodes.Cube004_2.material}
									/>
									<mesh
										geometry={nodes.Cube004_3.geometry}
										material={nodes.Cube004_3.material}
									/>
									<group position={[0.49, 0.68, 0.67]}>
										<mesh
											geometry={nodes.p6_ani001.geometry}
											material={nodes.p6_ani001.material}
										/>
										<mesh
											geometry={
												nodes.p6_ani001_1.geometry
											}
											material={
												nodes.p6_ani001_1.material
											}
										/>
										<mesh
											geometry={
												nodes.p6_ani001_2.geometry
											}
											material={
												nodes.p6_ani001_2.material
											}
										/>
									</group>
									<group position={[0.49, -0.68, -2.39]}>
										<mesh
											geometry={nodes.p6_ani002.geometry}
											material={nodes.p6_ani002.material}
										/>
										<mesh
											geometry={
												nodes.p6_ani002_1.geometry
											}
											material={
												nodes.p6_ani002_1.material
											}
										/>
										<mesh
											geometry={
												nodes.p6_ani002_2.geometry
											}
											material={
												nodes.p6_ani002_2.material
											}
										/>
									</group>
									<group position={[-1.44, 0, -0.85]}>
										<mesh
											geometry={nodes.p6_ani003.geometry}
											material={nodes.p6_ani003.material}
										/>
										<mesh
											geometry={
												nodes.p6_ani003_1.geometry
											}
											material={
												nodes.p6_ani003_1.material
											}
										/>
										<mesh
											geometry={
												nodes.p6_ani003_2.geometry
											}
											material={
												nodes.p6_ani003_2.material
											}
										/>
										<mesh
											geometry={
												nodes.p6_ani003_3.geometry
											}
											material={
												nodes.p6_ani003_3.material
											}
										/>
										<group position={[-13.49, 0.68, 1.52]}>
											<mesh
												geometry={
													nodes.p6_ani004.geometry
												}
												material={
													nodes.p6_ani004.material
												}
											/>
											<mesh
												geometry={
													nodes.p6_ani004_1.geometry
												}
												material={
													nodes.p6_ani004_1.material
												}
											/>
											<mesh
												geometry={
													nodes.p6_ani004_2.geometry
												}
												material={
													nodes.p6_ani004_2.material
												}
											/>
										</group>
										<group
											position={[-13.49, -0.68, -1.53]}
										>
											<mesh
												geometry={
													nodes.p6_ani005.geometry
												}
												material={
													nodes.p6_ani005.material
												}
											/>
											<mesh
												geometry={
													nodes.p6_ani005_1.geometry
												}
												material={
													nodes.p6_ani005_1.material
												}
											/>
											<mesh
												geometry={
													nodes.p6_ani005_2.geometry
												}
												material={
													nodes.p6_ani005_2.material
												}
											/>
										</group>
									</group>
								</group>
							</group>
							<group position={[-1.31, -2.25, 0]}>
								<mesh
									geometry={nodes.ESP3000.geometry}
									material={nodes.ESP3000.material}
								/>
								<mesh
									geometry={nodes.ESP3000_1.geometry}
									material={nodes.ESP3000_1.material}
								/>
								<mesh
									geometry={nodes.ESP3000_2.geometry}
									material={nodes.ESP3000_2.material}
								/>
								<mesh
									geometry={nodes.ESP3000_3.geometry}
									material={nodes.ESP3000_3.material}
								/>
								<mesh
									geometry={nodes.ESP3000_4.geometry}
									material={nodes.ESP3000_4.material}
								/>
							</group>
							<group position={[-1.84, 5.06, 0]}>
								<mesh
									geometry={nodes.esp2_lo000.geometry}
									material={nodes.esp2_lo000.material}
								/>
								<mesh
									geometry={nodes.esp2_lo000_1.geometry}
									material={nodes.esp2_lo000_1.material}
								/>
								<mesh
									geometry={nodes.esp2_lo000_2.geometry}
									material={nodes.esp2_lo000_2.material}
								/>
								<mesh
									geometry={nodes.esp2_lo000_3.geometry}
									material={nodes.esp2_lo000_3.material}
								/>
							</group>
							<group position={[2.21, -5.07, 0]}>
								<mesh
									geometry={nodes.esp2_lo001.geometry}
									material={nodes.esp2_lo001.material}
								/>
								<mesh
									geometry={nodes.esp2_lo001_1.geometry}
									material={nodes.esp2_lo001_1.material}
								/>
								<mesh
									geometry={nodes.esp2_lo001_2.geometry}
									material={nodes.esp2_lo001_2.material}
								/>
							</group>
							<group position={[2.11, 3.72, -0.24]}>
								<mesh
									geometry={nodes.AMS2000.geometry}
									material={nodes.AMS2000.material}
								/>
								<mesh
									geometry={nodes.AMS2000_1.geometry}
									material={nodes.AMS2000_1.material}
								/>
								<mesh
									geometry={nodes.AMS2000_2.geometry}
									material={nodes.AMS2000_2.material}
								/>
							</group>
						</group>
						<group position={[2.68, 1.91, 0.13]}>
							<mesh
								geometry={nodes.Cylinder023.geometry}
								material={nodes.Cylinder023.material}
							/>
							<mesh
								geometry={nodes.Cylinder023_1.geometry}
								material={nodes.Cylinder023_1.material}
							/>
							<mesh
								geometry={nodes.Cylinder023_2.geometry}
								material={nodes.Cylinder023_2.material}
							/>
						</group>
					</group>
					<group position={[6.82, 2.24, 1.5]}>
						<mesh
							geometry={nodes.s0_ani004.geometry}
							material={nodes.s0_ani004.material}
						/>
						<mesh
							geometry={nodes.s0_ani004_1.geometry}
							material={nodes.s0_ani004_1.material}
						/>
						<mesh
							geometry={nodes.s0_ani004_2.geometry}
							material={nodes.s0_ani004_2.material}
						/>
						<mesh
							geometry={nodes.s0_ani004_3.geometry}
							material={nodes.s0_ani004_3.material}
						/>
						<mesh
							geometry={nodes.s0_ani004_4.geometry}
							material={nodes.s0_ani004_4.material}
						/>
						<group position={[8.43, -2.23, -0.01]}>
							<mesh
								geometry={nodes.s0_ani005.geometry}
								material={nodes.s0_ani005.material}
							/>
							<mesh
								geometry={nodes.s0_ani005_1.geometry}
								material={nodes.s0_ani005_1.material}
							/>
							<mesh
								geometry={nodes.s0_ani005_2.geometry}
								material={nodes.s0_ani005_2.material}
							/>
							<mesh
								geometry={nodes.s0_ani005_3.geometry}
								material={nodes.s0_ani005_3.material}
							/>
						</group>
						<group position={[17.04, -2.23, 0.11]}>
							<mesh
								geometry={nodes.s0_ani006.geometry}
								material={nodes.s0_ani006.material}
							/>
							<mesh
								geometry={nodes.s0_ani006_1.geometry}
								material={nodes.s0_ani006_1.material}
							/>
							<mesh
								geometry={nodes.s0_ani006_2.geometry}
								material={nodes.s0_ani006_2.material}
							/>
							<group
								position={[3.02, 0.01, -0.03]}
								rotation={[Math.PI / 3, 0, 0]}
							>
								<mesh
									geometry={nodes.p6_ani006.geometry}
									material={nodes.p6_ani006.material}
								/>
								<mesh
									geometry={nodes.p6_ani006_1.geometry}
									material={nodes.p6_ani006_1.material}
								/>
								<mesh
									geometry={nodes.p6_ani006_2.geometry}
									material={nodes.p6_ani006_2.material}
								/>
								<mesh
									geometry={nodes.p6_ani006_3.geometry}
									material={nodes.p6_ani006_3.material}
								/>
								<mesh
									geometry={nodes.p6_ani006_4.geometry}
									material={nodes.p6_ani006_4.material}
								/>
								<group position={[8.14, -0.01, -1.23]}>
									<mesh
										geometry={nodes.Cube005.geometry}
										material={nodes.Cube005.material}
									/>
									<mesh
										geometry={nodes.Cube005_1.geometry}
										material={nodes.Cube005_1.material}
									/>
									<mesh
										geometry={nodes.Cube005_2.geometry}
										material={nodes.Cube005_2.material}
									/>
									<mesh
										geometry={nodes.Cube005_3.geometry}
										material={nodes.Cube005_3.material}
									/>
									<group position={[1.44, 0, 0.85]}>
										<mesh
											geometry={nodes.p6_ani007.geometry}
											material={nodes.p6_ani007.material}
										/>
										<mesh
											geometry={
												nodes.p6_ani007_1.geometry
											}
											material={
												nodes.p6_ani007_1.material
											}
										/>
										<mesh
											geometry={
												nodes.p6_ani007_2.geometry
											}
											material={
												nodes.p6_ani007_2.material
											}
										/>
										<mesh
											geometry={
												nodes.p6_ani007_3.geometry
											}
											material={
												nodes.p6_ani007_3.material
											}
										/>
										<group position={[13.49, -0.68, 1.53]}>
											<mesh
												geometry={
													nodes.p6_ani008.geometry
												}
												material={
													nodes.p6_ani008.material
												}
											/>
											<mesh
												geometry={
													nodes.p6_ani008_1.geometry
												}
												material={
													nodes.p6_ani008_1.material
												}
											/>
											<mesh
												geometry={
													nodes.p6_ani008_2.geometry
												}
												material={
													nodes.p6_ani008_2.material
												}
											/>
										</group>
										<group position={[13.49, 0.68, -1.52]}>
											<mesh
												geometry={
													nodes.p6_ani009.geometry
												}
												material={
													nodes.p6_ani009.material
												}
											/>
											<mesh
												geometry={
													nodes.p6_ani009_1.geometry
												}
												material={
													nodes.p6_ani009_1.material
												}
											/>
											<mesh
												geometry={
													nodes.p6_ani009_2.geometry
												}
												material={
													nodes.p6_ani009_2.material
												}
											/>
										</group>
									</group>
									<group position={[-0.49, -0.68, 2.39]}>
										<mesh
											geometry={nodes.p6_ani010.geometry}
											material={nodes.p6_ani010.material}
										/>
										<mesh
											geometry={
												nodes.p6_ani010_1.geometry
											}
											material={
												nodes.p6_ani010_1.material
											}
										/>
										<mesh
											geometry={
												nodes.p6_ani010_2.geometry
											}
											material={
												nodes.p6_ani010_2.material
											}
										/>
									</group>
									<group position={[-0.49, 0.68, -0.67]}>
										<mesh
											geometry={nodes.p6_ani011.geometry}
											material={nodes.p6_ani011.material}
										/>
										<mesh
											geometry={
												nodes.p6_ani011_1.geometry
											}
											material={
												nodes.p6_ani011_1.material
											}
										/>
										<mesh
											geometry={
												nodes.p6_ani011_2.geometry
											}
											material={
												nodes.p6_ani011_2.material
											}
										/>
									</group>
								</group>
							</group>
							<group position={[1.06, -5.07, -0.04]}>
								<mesh
									geometry={nodes.esp2_lo002.geometry}
									material={nodes.esp2_lo002.material}
								/>
								<mesh
									geometry={nodes.esp2_lo002_1.geometry}
									material={nodes.esp2_lo002_1.material}
								/>
								<mesh
									geometry={nodes.esp2_lo002_2.geometry}
									material={nodes.esp2_lo002_2.material}
								/>
								<mesh
									geometry={nodes.esp2_lo002_3.geometry}
									material={nodes.esp2_lo002_3.material}
								/>
							</group>
							<group position={[1.84, 5.06, -0.07]}>
								<mesh
									geometry={nodes.esp2_lo003.geometry}
									material={materials.ISS_AO_08}
								/>
								<mesh
									geometry={nodes.esp2_lo003_1.geometry}
									material={nodes.esp2_lo003_1.material}
								/>
								<mesh
									geometry={nodes.esp2_lo003_2.geometry}
									material={nodes.esp2_lo003_2.material}
								/>
								<mesh
									geometry={nodes.esp2_lo003_3.geometry}
									material={nodes.esp2_lo003_3.material}
								/>
							</group>
						</group>
					</group>
				</group>
				<group position={[0, 0, 9.16]}>
					<mesh
						geometry={nodes.Cylinder024.geometry}
						material={nodes.Cylinder024.material}
					/>
					<mesh
						geometry={nodes.Cylinder024_1.geometry}
						material={nodes.Cylinder024_1.material}
					/>
					<mesh
						geometry={nodes.Cylinder024_2.geometry}
						material={nodes.Cylinder024_2.material}
					/>
					<mesh
						geometry={nodes.Cylinder024_3.geometry}
						material={nodes.Cylinder024_3.material}
					/>
					<group position={[0, 0, 6.97]}>
						<mesh
							geometry={nodes.Cylinder025.geometry}
							material={nodes.Cylinder025.material}
						/>
						<mesh
							geometry={nodes.Cylinder025_1.geometry}
							material={nodes.Cylinder025_1.material}
						/>
						<mesh
							geometry={nodes.Cylinder025_2.geometry}
							material={nodes.Cylinder025_2.material}
						/>
					</group>
					<group position={[-4.17, 0, 4.83]}>
						<mesh
							geometry={nodes.Cylinder026.geometry}
							material={nodes.Cylinder026.material}
						/>
						<mesh
							geometry={nodes.Cylinder026_1.geometry}
							material={nodes.Cylinder026_1.material}
						/>
						<mesh
							geometry={nodes.Cylinder026_2.geometry}
							material={nodes.Cylinder026_2.material}
						/>
						<mesh
							geometry={nodes.Cylinder026_3.geometry}
							material={nodes.Cylinder026_3.material}
						/>
						<mesh
							geometry={nodes.Cylinder026_4.geometry}
							material={nodes.Cylinder026_4.material}
						/>
						<mesh
							geometry={nodes.Cylinder026_5.geometry}
							material={nodes.Cylinder026_5.material}
						/>
						<group position={[-5.9, -1.33, 0]}>
							<mesh
								geometry={nodes.Cube006.geometry}
								material={nodes.Cube006.material}
							/>
							<mesh
								geometry={nodes.Cube006_1.geometry}
								material={nodes.Cube006_1.material}
							/>
							<mesh
								geometry={nodes.Cube006_2.geometry}
								material={nodes.Cube006_2.material}
							/>
							<mesh
								geometry={nodes.Cube006_3.geometry}
								material={nodes.Cube006_3.material}
							/>
							<mesh
								geometry={nodes.RapidScat_dish.geometry}
								material={nodes.RapidScat_dish.material}
								position={[-0.73, -0.83, -0.22]}
							/>
						</group>
					</group>
					<group position={[7.48, 0, 4.83]}>
						<mesh
							geometry={nodes.Cylinder027.geometry}
							material={nodes.Cylinder027.material}
						/>
						<mesh
							geometry={nodes.Cylinder027_1.geometry}
							material={nodes.Cylinder027_1.material}
						/>
						<mesh
							geometry={nodes.Cylinder027_2.geometry}
							material={nodes.Cylinder027_2.material}
						/>
						<mesh
							geometry={nodes.Cylinder027_3.geometry}
							material={nodes.Cylinder027_3.material}
						/>
						<mesh
							geometry={nodes.Cylinder027_4.geometry}
							material={nodes.Cylinder027_4.material}
						/>
						<mesh
							geometry={nodes.Cylinder027_5.geometry}
							material={nodes.Cylinder027_5.material}
						/>
						<group position={[2.82, 4.04, 0]}>
							<mesh
								geometry={nodes.Cylinder028.geometry}
								material={nodes.Cylinder028.material}
							/>
							<mesh
								geometry={nodes.Cylinder028_1.geometry}
								material={nodes.Cylinder028_1.material}
							/>
							<mesh
								geometry={nodes.Cylinder028_2.geometry}
								material={nodes.Cylinder028_2.material}
							/>
							<mesh
								geometry={nodes.Cylinder028_3.geometry}
								material={nodes.Cylinder028_3.material}
							/>
							<mesh
								geometry={nodes.Cylinder028_4.geometry}
								material={nodes.Cylinder028_4.material}
							/>
							<mesh
								geometry={nodes.Cylinder028_5.geometry}
								material={nodes.Cylinder028_5.material}
							/>
						</group>
						<mesh
							geometry={nodes['31_Robotic_Arm'].geometry}
							material={nodes['31_Robotic_Arm'].material}
							position={[5.14, 0.88, 1.68]}
						>
							<mesh
								geometry={nodes['31_Robotic_Arm001'].geometry}
								material={nodes['31_Robotic_Arm001'].material}
								position={[0.76, 0.3, -0.33]}
							>
								<mesh
									geometry={
										nodes['31_Robotic_Arm002'].geometry
									}
									material={
										nodes['31_Robotic_Arm002'].material
									}
									position={[0, 0.41, 0.53]}
								>
									<mesh
										geometry={
											nodes['31_Robotic_Arm003'].geometry
										}
										material={
											nodes['31_Robotic_Arm003'].material
										}
										position={[4.07, 0, -0.54]}
									>
										<mesh
											geometry={
												nodes['31_Robotic_Arm004']
													.geometry
											}
											material={
												nodes['31_Robotic_Arm004']
													.material
											}
											position={[4.07, 0, -0.52]}
										>
											<mesh
												geometry={
													nodes['31_Robotic_Arm005']
														.geometry
												}
												material={
													nodes['31_Robotic_Arm005']
														.material
												}
												position={[0.44, 0.52, 0.01]}
											/>
										</mesh>
									</mesh>
								</mesh>
							</mesh>
						</mesh>
						<group position={[6.05, -1.56, -0.09]}>
							<mesh
								geometry={nodes.Cube009.geometry}
								material={nodes.Cube009.material}
							/>
							<mesh
								geometry={nodes.Cube009_1.geometry}
								material={nodes.Cube009_1.material}
							/>
							<mesh
								geometry={nodes.Cube009_2.geometry}
								material={nodes.Cube009_2.material}
							/>
							<mesh
								geometry={nodes.Cube009_3.geometry}
								material={nodes.Cube009_3.material}
							/>
						</group>
						<group position={[10.49, -1.95, -1.08]}>
							<mesh
								geometry={nodes.Cube010.geometry}
								material={nodes.Cube010.material}
							/>
							<mesh
								geometry={nodes.Cube010_1.geometry}
								material={nodes.Cube010_1.material}
							/>
						</group>
					</group>
				</group>
				<mesh
					geometry={nodes.Destiny_Window_Cover.geometry}
					material={nodes.Destiny_Window_Cover.material}
					position={[0, -2.32, 4.78]}
				/>
			</group>
			<group position={[-3.69, -0.37, 0]}>
				<mesh
					geometry={nodes.Cylinder034.geometry}
					material={nodes.Cylinder034.material}
				/>
				<mesh
					geometry={nodes.Cylinder034_1.geometry}
					material={nodes.Cylinder034_1.material}
				/>
				<mesh
					geometry={nodes.Cylinder034_2.geometry}
					material={nodes.Cylinder034_2.material}
				/>
				<mesh
					geometry={nodes.Cylinder034_3.geometry}
					material={nodes.Cylinder034_3.material}
				/>
				<mesh
					geometry={nodes.Cylinder034_4.geometry}
					material={nodes.Cylinder034_4.material}
				/>
				<mesh
					geometry={nodes.Cylinder034_5.geometry}
					material={nodes.Cylinder034_5.material}
				/>
				<mesh
					geometry={nodes.Cylinder034_6.geometry}
					material={nodes.Cylinder034_6.material}
				/>
				<group position={[0.64, 0, 2.43]}>
					<mesh
						geometry={nodes.esp2_lo004.geometry}
						material={nodes.esp2_lo004.material}
					/>
					<mesh
						geometry={nodes.esp2_lo004_1.geometry}
						material={nodes.esp2_lo004_1.material}
					/>
					<mesh
						geometry={nodes.esp2_lo004_2.geometry}
						material={nodes.esp2_lo004_2.material}
					/>
					<mesh
						geometry={nodes.esp2_lo004_3.geometry}
						material={nodes.esp2_lo004_3.material}
					/>
				</group>
			</group>
			<group position={[2.23, 0, 0]}>
				<mesh
					geometry={nodes.Cylinder035.geometry}
					material={nodes.Cylinder035.material}
				/>
				<mesh
					geometry={nodes.Cylinder035_1.geometry}
					material={nodes.Cylinder035_1.material}
				/>
				<mesh
					geometry={nodes.Cylinder035_2.geometry}
					material={nodes.Cylinder035_2.material}
				/>
				<mesh
					geometry={nodes.Cylinder035_3.geometry}
					material={nodes.Cylinder035_3.material}
				/>
				<group position={[6.97, 0, 0]}>
					<mesh
						geometry={nodes.Cylinder036.geometry}
						material={nodes.Cylinder036.material}
					/>
					<mesh
						geometry={nodes.Cylinder036_1.geometry}
						material={nodes.Cylinder036_1.material}
					/>
					<mesh
						geometry={nodes.Cylinder036_2.geometry}
						material={nodes.Cylinder036_2.material}
					/>
				</group>
				<group position={[4.83, -2.62, 0]}>
					<mesh
						geometry={nodes.Cylinder037.geometry}
						material={nodes.Cylinder037.material}
					/>
					<mesh
						geometry={nodes.Cylinder037_1.geometry}
						material={nodes.Cylinder037_1.material}
					/>
					<mesh
						geometry={nodes.Cylinder037_2.geometry}
						material={nodes.Cylinder037_2.material}
					/>
					<mesh
						geometry={nodes['38_Cupola001'].geometry}
						material={nodes['38_Cupola001'].material}
						position={[1.2, -0.36, -0.01]}
					/>
					<mesh
						geometry={nodes['38_Cupola002'].geometry}
						material={nodes['38_Cupola002'].material}
						position={[0.58, -0.36, 1.05]}
					/>
					<mesh
						geometry={nodes['38_Cupola003'].geometry}
						material={nodes['38_Cupola003'].material}
						position={[-0.57, -0.36, 1.05]}
					/>
					<mesh
						geometry={nodes['38_Cupola004'].geometry}
						material={nodes['38_Cupola004'].material}
						position={[-1.2, -0.36, 0]}
					/>
					<mesh
						geometry={nodes['38_Cupola005'].geometry}
						material={nodes['38_Cupola005'].material}
						position={[-0.58, -0.36, -1.05]}
					/>
					<mesh
						geometry={nodes['38_Cupola006'].geometry}
						material={nodes['38_Cupola006'].material}
						position={[0.62, -0.36, -1.03]}
					/>
					<mesh
						geometry={nodes['38_Cupola007'].geometry}
						material={nodes['38_Cupola007'].material}
						position={[-0.62, -1.05, 0.3]}
					/>
					<mesh
						geometry={nodes.ISS.geometry}
						material={nodes.ISS.material}
						position={[0, -0.02, 0]}
					/>
				</group>
			</group>
			<group position={[0, -2.19, 0]}>
				<mesh
					geometry={nodes.Cylinder040.geometry}
					material={nodes.Cylinder040.material}
				/>
				<mesh
					geometry={nodes.Cylinder040_1.geometry}
					material={nodes.Cylinder040_1.material}
				/>
				<mesh
					geometry={nodes.Cylinder040_2.geometry}
					material={nodes.Cylinder040_2.material}
				/>
				<mesh
					geometry={nodes.Cylinder040_3.geometry}
					material={nodes.Cylinder040_3.material}
				/>
				<mesh
					geometry={nodes.Cylinder040_4.geometry}
					material={nodes.Cylinder040_4.material}
				/>
			</group>
			<group position={[1.69, 0.85, -11.09]}>
				<mesh
					geometry={nodes.Cube017.geometry}
					material={nodes.Cube017.material}
				/>
				<mesh
					geometry={nodes.Cube017_1.geometry}
					material={nodes.Cube017_1.material}
				/>
			</group>
			<mesh
				geometry={nodes.hinge_02_p.geometry}
				material={nodes.hinge_02_p.material}
				position={[2.17, 0.8, -12.51]}
			/>
			<group position={[2.94, 0.8, -9.63]}>
				<mesh
					geometry={nodes.Cube019.geometry}
					material={nodes.Cube019.material}
				/>
				<mesh
					geometry={nodes.Cube019_1.geometry}
					material={nodes.Cube019_1.material}
				/>
			</group>
			<mesh
				geometry={nodes.hinge_04_p.geometry}
				material={nodes.hinge_04_p.material}
				position={[3.91, 0.8, -12.5]}
			/>
			<mesh
				geometry={nodes.hinge_01_p.geometry}
				material={nodes.hinge_01_p.material}
				position={[1.69, 0.8, -11.09]}
			/>
			<group position={[2.17, 0.8, -9.66]}>
				<mesh
					geometry={nodes.Cube022.geometry}
					material={nodes.Cube022.material}
				/>
				<mesh
					geometry={nodes.Cube022_1.geometry}
					material={nodes.Cube022_1.material}
				/>
			</group>
			<mesh
				geometry={nodes.hinge_03_p.geometry}
				material={nodes.hinge_03_p.material}
				position={[2.93, 0.8, -12.54]}
			/>
			<group position={[3.91, 0.8, -9.68]}>
				<mesh
					geometry={nodes.Cube024.geometry}
					material={nodes.Cube024.material}
				/>
				<mesh
					geometry={nodes.Cube024_1.geometry}
					material={nodes.Cube024_1.material}
				/>
			</group>
			<group position={[-1.69, 0.85, -11.09]}>
				<mesh
					geometry={nodes.Cube025.geometry}
					material={nodes.Cube025.material}
				/>
				<mesh
					geometry={nodes.Cube025_1.geometry}
					material={nodes.Cube025_1.material}
				/>
			</group>
			<mesh
				geometry={nodes.hinge_02_s.geometry}
				material={nodes.hinge_02_s.material}
				position={[-2.17, 0.8, -12.51]}
			/>
			<group position={[-2.94, 0.8, -9.63]}>
				<mesh
					geometry={nodes.Cube027.geometry}
					material={nodes.Cube027.material}
				/>
				<mesh
					geometry={nodes.Cube027_1.geometry}
					material={nodes.Cube027_1.material}
				/>
			</group>
			<mesh
				geometry={nodes.hinge_04_s.geometry}
				material={nodes.hinge_04_s.material}
				position={[-3.91, 0.8, -12.5]}
			/>
			<mesh
				geometry={nodes.hinge_03_s.geometry}
				material={nodes.hinge_03_s.material}
				position={[-2.93, 0.8, -12.54]}
			/>
			<group position={[-3.91, 0.8, -9.68]}>
				<mesh
					geometry={nodes.Cube030.geometry}
					material={nodes.Cube030.material}
				/>
				<mesh
					geometry={nodes.Cube030_1.geometry}
					material={nodes.Cube030_1.material}
				/>
			</group>
			<group position={[-2.17, 0.8, -9.66]}>
				<mesh
					geometry={nodes.Cube031.geometry}
					material={nodes.Cube031.material}
				/>
				<mesh
					geometry={nodes.Cube031_1.geometry}
					material={nodes.Cube031_1.material}
				/>
			</group>
			<mesh
				geometry={nodes.hinge_01_s.geometry}
				material={nodes.hinge_01_s.material}
				position={[-1.69, 0.8, -11.09]}
			/>
			<group position={[15.53, -2.12, 19.9]}>
				<mesh
					geometry={nodes.Cube033.geometry}
					material={materials.white}
				/>
				<mesh
					geometry={nodes.Cube033_1.geometry}
					material={materials.base_metal}
				/>
				<mesh
					geometry={nodes.Cube033_2.geometry}
					material={nodes.Cube033_2.material}
				/>
				<mesh
					geometry={nodes.Cube033_3.geometry}
					material={materials['ISS_03_dull.001']}
				/>
			</group>
			<group position={[18.91, -1.96, 16.11]}>
				<mesh
					geometry={nodes.Cylinder041.geometry}
					material={materials.ecostress}
				/>
				<mesh
					geometry={nodes.Cylinder041_1.geometry}
					material={materials['plastic black']}
				/>
				<mesh
					geometry={nodes.Cylinder041_2.geometry}
					material={materials.ecostressWhite}
				/>
				<mesh
					geometry={nodes.Cylinder041_3.geometry}
					material={materials['ISS_03_dull.002']}
				/>
				<mesh
					geometry={nodes.Cylinder041_4.geometry}
					material={materials['ecostress metal']}
				/>
				<mesh
					geometry={nodes.Cylinder041_5.geometry}
					material={nodes.Cylinder041_5.material}
				/>
				<mesh
					geometry={nodes.Cylinder041_6.geometry}
					material={materials.ecostress_dexter}
				/>
			</group>
		</animated.group>
	);
}

useGLTF.preload(path);
